Switch to MIT license
2DegreesInvesting/r2dii.match pull request #286
Opened 2020-09-10 10:36 UTC by jdhoffa

Before merging this PR, we will need approval from all contributors.

2020-09-10 11:23 UTC, maurolepore requested changes
DESCRIPTION still mentions the old license. `usethis::use_mit_license()` should do the trick.

2020-09-10 11:25 UTC, maurolepore commented
I approve changing to MIT license. 

For convenience I show here the other authors. Would you like me to contact them?

```
Authors@R: 
    c(person(given = "Mauro",
             family = "Lepore",
             role = c("aut", "cre", "ctr"),
             email = "maurolepore@gmail.com",
             comment = c(ORCID = "0000-0002-1986-7988")),
      person(given = "Jackson",
             family = "Hoffart",
             role = "aut",
             email = "jackson@2degrees-investing.org",
             comment = c(ORCID = "0000-0002-8600-5042")),
      person(given = "Klaus",
             family = "Hagedorn",
             role = "aut",
             email = "klaus@2degrees-investing.org"),
      person(given = "Florence",
             family = "Palandri",
             role = "aut",
             email = "florence@2degrees-investing.org"),
      person(given = "Evgeny",
             family = "Petrovsky",
             role = "aut"),
      person(given = "2 Degrees Investing Initiative",
             role = c("cph", "fnd"),
             email = "contact@2degrees-investing.org"))
```

2020-09-10 11:47 UTC, jdhoffa commented
Yes, thanks Mauro, that would be great

2020-09-10 12:15 UTC, jdhoffa commented
I approve the change to MIT license.

2020-09-10 12:24 UTC, maurolepore commented
All authors mentioned here,

- [  ] @maurolepore 
- [  ] @jdhoffa 
- [  ] @2diiKlaus 
- [  ] @fpalandri
- [  ] @EvgenyPetrovsky
- [  ] 2 Degrees Investing Initiative (contact@2degrees-investing.org)


We plan to change the license of this package to MIT and we need all authors to support the change. For details contact @jdhoffa  or @AlexAxthelm. If you support the change, please write a comment in this thread ASAP, e.g. 

> I support changing the license of this package to MIT.

2020-09-10 12:24 UTC, maurolepore commented
I support changing the license of this package to MIT.

2020-09-10 13:34 UTC, fpalandri commented
I support changing the license of this package to MIT.

2020-09-10 13:34 UTC, fpalandri commented
I support changing the license of this package to MIT.

2020-09-10 13:34 UTC, fpalandri commented
I support changing the license of this package to MIT.

2020-09-10 16:09 UTC, 2diiKlaus commented
I support changing the license of this package to MIT.

2020-09-11 06:08 UTC, EvgenyPetrovsky commented
I approve changing to MIT license.

2020-09-11 11:55 UTC, maurolepore requested changes
Please run the helper from usethis, as I think a file is missing.

2020-09-11 11:55 UTC, maurolepore commented on LICENSE
> +COPYRIGHT HOLDER: 2 Degrees Investing Initiative France
Can you confirm we need the word "France"?

2020-09-11 13:48 UTC, jdhoffa commented on LICENSE
> +COPYRIGHT HOLDER: 2 Degrees Investing Initiative France
yes

2020-09-11 17:37 UTC, maurolepore approved these changes

2020-09-11 17:38 UTC, maurolepore commented
Directors of 2DII investing confirmed they also support the change to MIT license. So we are ready to merge.

2020-09-11 17:41 UTC, merged